kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thesis-energyscience-pdfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Mi
  storageClassName: netapp
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thesis-susdev-pdfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: netapp
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thesis-watermgmt-pdfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 850Mi
  storageClassName: netapp
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thesis-sbi-pdfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 700Mi
  storageClassName: netapp
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: thesis-innosci-pdfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: netapp
  volumeMode: Filesystem