[server]
enableStaticServing = true
showEmailPrompt = false

[logger]
level = "info"

[client]
showErrorDetails = "none"

[browser]
gatherUsageStats = false
serverAddress = "test-thesisexplorer.geo.uu.nl"